set SynModuleInfo {
  {SRCNAME bubble_sort_Pipeline_VITIS_LOOP_21_4 MODELNAME bubble_sort_Pipeline_VITIS_LOOP_21_4 RTLNAME bubble_sort_bubble_sort_Pipeline_VITIS_LOOP_21_4
    SUBMODULES {
      {MODELNAME bubble_sort_flow_control_loop_pipe_sequential_init RTLNAME bubble_sort_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME bubble_sort_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME bubble_sort_Pipeline_VITIS_LOOP_39_6 MODELNAME bubble_sort_Pipeline_VITIS_LOOP_39_6 RTLNAME bubble_sort_bubble_sort_Pipeline_VITIS_LOOP_39_6}
  {SRCNAME bubble_sort_Pipeline_VITIS_LOOP_61_1 MODELNAME bubble_sort_Pipeline_VITIS_LOOP_61_1 RTLNAME bubble_sort_bubble_sort_Pipeline_VITIS_LOOP_61_1}
  {SRCNAME bubble_sort MODELNAME bubble_sort RTLNAME bubble_sort IS_TOP 1}
}
